name: F-Prop Aerials
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2927'
    - '#f8f8f8'
    - '#4b4841'
    - '#8e8485'
    - '#e5c7ab'
  brandStrength: 0.665093572344631
  lightness: 0.23026480991393328
  saturation: 0.6373779911082238
  rhythmicContrast: 0.8153529071714729
purpose: []
