name: F-Prop Aerials
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02354a'
    - '#050100'
    - '#bcc2c2'
    - '#067ab7'
    - '#633d13'
  brandStrength: 0
  lightness: 0.23026480991393328
  saturation: 0.6373779911082238
  rhythmicContrast: 0.8153529071714729
purpose: []
