name: F-Prop Aerials
favicon: null
layout_spectrum: 0.49619
typography_spectrum: 0.74838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02354a'
    - '#050100'
    - '#bcc2c2'
    - '#067ab7'
    - '#633d13'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
